<select class="form-select" name="code_pays" id="code_pays" required>
    <option value="" disabled selected>--Pays--</option>
    <option value="+93">Afghanistan</option>
    <option value="+355">Albanie</option>
    <option value="+213">Algérie</option>
    <option value="+376">Andorre</option>
    <option value="+244">Angola</option>
    <option value="+54">Argentine</option>
    <option value="+374">Arménie</option>
    <option value="+61">Australie</option>
    <option value="+43">Autriche</option>
    <option value="+994">Azerbaïdjan</option>
    <option value="+973">Bahreïn</option>
    <option value="+880">Bangladesh</option>
    <option value="+375">Biélorussie</option>
    <option value="+32">Belgique</option>
    <option value="+229">Bénin</option>
    <option value="+975">Bhoutan</option>
    <option value="+591">Bolivie</option>
    <option value="+387">Bosnie-Herzégovine</option>
    <option value="+267">Botswana</option>
    <option value="+55">Brésil</option>
    <option value="+359">Bulgarie</option>
    <option value="+226">Burkina Faso</option>
    <option value="+257">Burundi</option>
    <option value="+855">Cambodge</option>
    <option value="+237">Cameroun</option>
    <option value="+1">Canada</option>
    <option value="+238">Cap-Vert</option>
    <option value="+236">République Centrafricaine</option>
    <option value="+235">Tchad</option>
    <option value="+56">Chili</option>
    <option value="+86">Chine</option>
    <option value="+57">Colombie</option>
    <option value="+269">Comores</option>
    <option value="+243">République Démocratique du Congo</option>
    <option value="+242">Congo</option>
    <option value="+682">Îles Cook</option>
    <option value="+506">Costa Rica</option>
    <option value="+225">Côte d'Ivoire</option>
    <option value="+385">Croatie</option>
    <option value="+53">Cuba</option>
    <option value="+357">Chypre</option>
    <option value="+420">République Tchèque</option>
    <option value="+45">Danemark</option>
    <option value="+253">Djibouti</option>
    <option value="+1 767">Dominique</option>
    <option value="+593">Équateur</option>
    <option value="+20">Égypte</option>
    <option value="+503">Salvador</option>
    <option value="+240">Guinée équatoriale</option>
    <option value="+291">Érythrée</option>
    <option value="+372">Estonie</option>
    <option value="+251">Éthiopie</option>
    <option value="+679">Fidji</option>
    <option value="+358">Finlande</option>
    <option value="+33">France</option>
    <option value="+241">Gabon</option>
    <option value="+220">Gambie</option>
    <option value="+995">Géorgie</option>
    <option value="+49">Allemagne</option>
    <option value="+233">Ghana</option>
    <option value="+30">Grèce</option>
    <option value="+502">Guatemala</option>
    <option value="+224">Guinée</option>
    <option value="+245">Guinée-Bissau</option>
    <option value="+592">Guyana</option>
    <option value="+509">Haïti</option>
    <option value="+504">Honduras</option>
    <option value="+36">Hongrie</option>
    <option value="+354">Islande</option>
    <option value="+91">Inde</option>
    <option value="+62">Indonésie</option>
    <option value="+98">Iran</option>
    <option value="+964">Irak</option>
    <option value="+353">Irlande</option>
    <option value="+972">Israël</option>
    <option value="+39">Italie</option>
    <option value="+81">Japon</option>
    <option value="+962">Jordanie</option>
    <option value="+7">Kazakhstan</option>
    <option value="+254">Kenya</option>
    <option value="+686">Kiribati</option>
    <option value="+383">Kosovo</option>
    <option value="+965">Koweït</option>
    <option value="+996">Kirghizistan</option>
    <option value="+856">Laos</option>
    <option value="+371">Lettonie</option>
    <option value="+961">Liban</option>
    <option value="+266">Lesotho</option>
    <option value="+231">Liberia</option>
    <option value="+218">Libye</option>
    <option value="+423">Liechtenstein</option>
    <option value="+370">Lituanie</option>
    <option value="+352">Luxembourg</option>
    <option value="+389">Macédoine</option>
    <option value="+261">Madagascar</option>
    <option value="+265">Malawi</option>
    <option value="+60">Malaisie</option>
    <option value="+960">Maldives</option>
    <option value="+223">Mali</option>
    <option value="+356">Malte</option>
    <option value="+692">Îles Marshall</option>
    <option value="+222">Mauritanie</option>
    <option value="+230">Maurice</option>
    <option value="+52">Mexique</option>
    <option value="+691">Micronésie</option>
    <option value="+373">Moldavie</option>
    <option value="+377">Monaco</option>
    <option value="+976">Mongolie</option>
    <option value="+382">Monténégro</option>
    <option value="+212">Maroc</option>
    <option value="+258">Mozambique</option>
    <option value="+95">Myanmar</option>
    <option value="+264">Namibie</option>
    <option value="+674">Nauru</option>
    <option value="+977">Népal</option>
    <option value="+31">Pays-Bas</option>
    <option value="+64">Nouvelle-Zélande</option>
    <option value="+505">Nicaragua</option>
    <option value="+227">Niger</option>
    <option value="+234">Nigéria</option>
    <option value="+47">Norvège</option>
    <option value="+968">Oman</option>
    <option value="+92">Pakistan</option>
    <option value="+680">Palaos</option>
    <option value="+507">Panama</option>
    <option value="+675">Papouasie-Nouvelle-Guinée</option>
    <option value="+595">Paraguay</option>
    <option value="+51">Pérou</option>
    <option value="+63">Philippines</option>
    <option value="+48">Pologne</option>
    <option value="+351">Portugal</option>
    <option value="+974">Qatar</option>
    <option value="+262">Réunion</option>
    <option value="+40">Roumanie</option>
    <option value="+7">Russie</option>
    <option value="+250">Rwanda</option>
    <option value="+685">Samoa</option>
    <option value="+378">Saint-Marin</option>
    <option value="+239">Sao Tomé-et-Principe</option>
    <option value="+966">Arabie Saoudite</option>
    <option value="+221">Sénégal</option>
    <option value="+381">Serbie</option>
    <option value="+248">Seychelles</option>
    <option value="+232">Sierra Leone</option>
    <option value="+65">Singapour</option>
    <option value="+421">Slovaquie</option>
    <option value="+386">Slovénie</option>
    <option value="+677">Îles Salomon</option>
    <option value="+252">Somalie</option>
    <option value="+27">Afrique du Sud</option>
    <option value="+82">Corée du Sud</option>
    <option value="+34">Espagne</option>
    <option value="+94">Sri Lanka</option>
    <option value="+249">Soudan</option>
    <option value="+597">Suriname</option>
    <option value="+268">Swaziland</option>
   
</select>